### ISSUE TITLE
[BUG] DO fails to build

### ISSUE THREAD

**Issue by BlackDahlia313** [TwixGamer00/Azuri#3]
Using Digital Ocean to build the docker image. It runs fine and bot works for about 3 minutes, but when build cycle finishes it kills the bot and gives general error.

Cant find any more info in DO apps section about it.

**Comment by BlackDahlia313** [comment]
Trying to use a nodejs server in the meantime and seeing this:

> /home/nodejs/Azuri/src/node_modules/discord.js/src/rest/RESTManager.js:32
    const token = this.client.token ?? this.client.accessToken;
                                     ^

> SyntaxError: Unexpected token '?'

    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/nodejs/Azuri/src/node_modules/discord.js/src/client/BaseClient.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by finnie2006** [comment]
Whay do you mean with build cycle :D

**Comment by finnie2006** [comment]
@BlackDahlia313

**Comment by finnie2006** [comment]
Closed due to inactivity
