### ISSUE TITLE
[BUG] Bot won't start - error in WebSocketManager

### ISSUE THREAD

**Issue by taiBsu** [TwixGamer00/Azuri#5]
**Describe the bug**
After starting the container, I get the following log output:

```
Creating network "azura_discord_default" with the default driver
Creating azura_discord_azuri_1 ... done
Attaching to azura_discord_azuri_1
azuri_1  |
azuri_1  | added 63 packages, and audited 64 packages in 6s
azuri_1  |
azuri_1  | 6 packages are looking for funding
azuri_1  |   run `npm fund` for details
azuri_1  |
azuri_1  | 1 moderate severity vulnerability
azuri_1  |
azuri_1  | To address all issues, run:
azuri_1  |   npm audit fix
azuri_1  |
azuri_1  | Run `npm audit` for details.
azuri_1  | npm notice
azuri_1  | npm notice New minor version of npm available! 8.3.1 -> 8.5.0
azuri_1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.0>
azuri_1  | npm notice Run `npm install -g npm@8.5.0` to update!
azuri_1  | npm notice
azuri_1  |
azuri_1  | > azuri@2.0.0 azuri
azuri_1  | > node app.mjs
azuri_1  |
azuri_1  | Starting Shard: 0
azuri_1  | Registered Command - join
azuri_1  | Registered Command - help
azuri_1  | Registered Command - leave
azuri_1  | Registered Command - playing
azuri_1  | Registered Command - ping
azuri_1  | Registered Command - recent
azuri_1  | Registered Command - stats
azuri_1  | Registered Command - support
azuri_1  | Registered Command - settings
azuri_1  | Registered Command - tuned
azuri_1  | /data/node_modules/discord.js/src/client/websocket/WebSocketManager.js:244
azuri_1  |         throw new Error(WSCodes[error.code]);
azuri_1  |               ^
azuri_1  |
azuri_1  | Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
azuri_1  |     at WebSocketManager.createShards (/data/node_modules/discord.js/src/client/websocket/WebSocketManager.js:244:15)
azuri_1  |     at async Client.login (/data/node_modules/discord.js/src/client/Client.js:245:7) {
azuri_1  |   [Symbol(code)]: 'DISALLOWED_INTENTS'
azuri_1  | }
azuri_1  | /data/node_modules/discord.js/src/sharding/Shard.js:160
azuri_1  |         reject(new Error('SHARDING_READY_DIED', this.id));
azuri_1  |                ^
azuri_1  |
azuri_1  | Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
azuri_1  |     at Shard.onDeath (/data/node_modules/discord.js/src/sharding/Shard.js:160:16)
azuri_1  |     at Object.onceWrapper (node:events:640:26)
azuri_1  |     at Shard.emit (node:events:520:28)
azuri_1  |     at Shard._handleExit (/data/node_modules/discord.js/src/sharding/Shard.js:392:10)
azuri_1  |     at ChildProcess.emit (node:events:520:28)
azuri_1  |     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
azuri_1  |   [Symbol(code)]: 'SHARDING_READY_DIED'
azuri_1  | }
```

**To Reproduce**
Steps to reproduce the behaviour:
1. git clone azuri
2. copy and edit env file
3. docker-compose up -d

**Expected behaviour**
Bot should startup normally.

**Smartphone (please complete the following information):**
 - Device: Desktop PC
 - OS: Xubuntu 20.04

**Comment by fnfzlznddzn** [comment]
Hey, I'm having the same return when I run `docker-compose up`  after cloning the repo with `git clone https://github.com/TwixGamer00/Azuri` did you manage to fix it @taiBsu ?

I am running Docker Desktop in Windows with WSL 2/Ubuntu.

**Comment by fnfzlznddzn** [comment]
fixed: see https://stackoverflow.com/questions/64006888/can-anyone-explain-the-issue

> You'll have to go to [Discord Developer Portal](https://discord.com/developers/applications/), choose your application, go to the Bot section, and enable all the intents. (Or the ones you are using.)

**Comment by taiBsu** [comment]
Thanks @fnfzlznddzn, I'll have a look at that.

**Comment by finnie2006** [comment]
Yeah, this error does not have anything to do with the bot itself, you just have to enable intents.
If you have any further questions make a new issue or reopen
