### ISSUE TITLE
Error in nowplaying.mjs

### ISSUE THREAD

**Issue by WiredDesigns** [TwixGamer00/Azuri#6]
``RangeError [EMBED_FIELD_NAME]: MessageEmbed field names must be non-empty strings.
    at Function.verifyString (/workspace/Fortenox/Azuri-main/src/node_modules/discord.js/src/util/Util.js:414:49)
    at Function.normalizeField (/workspace/Fortenox/Azuri-main/src/node_modules/discord.js/src/structures/MessageEmbed.js:442:18)
    at /workspace/Fortenox/Azuri-main/src/node_modules/discord.js/src/structures/MessageEmbed.js:464:14
    at Array.map (<anonymous>)
    at Function.normalizeFields (/workspace/Fortenox/Azuri-main/src/node_modules/discord.js/src/structures/MessageEmbed.js:463:8)
    at MessageEmbed.addFields (/workspace/Fortenox/Azuri-main/src/node_modules/discord.js/src/structures/MessageEmbed.js:286:42)
    at file:///workspace/Fortenox/Azuri-main/src/commands/nowPlaying.mjs:30:12
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [Symbol(code)]: 'EMBED_FIELD_NAME'
}
file:///workspace/Fortenox/Azuri-main/src/locale/locales.mjs:16
  if (!locales[locale][key]) return `${key} was not found`;
                      ^

TypeError: Cannot read properties of undefined (reading 'undefined')
    at Module._U (file:///workspace/Fortenox/Azuri-main/src/locale/locales.mjs:16:23)
    at file:///workspace/Fortenox/Azuri-main/src/commands/nowPlaying.mjs:40:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`` I get this error in Nowplaying.mjs Ive sat everything up like it should, with api, but this comes still

**Comment by finnie2006** [comment]
Your probaply set the wrong url
