### ISSUE TITLE
[BUG] Bot isnt starting

### ISSUE THREAD

**Issue by SDS1234** [TwixGamer00/Azuri#8]
Bot isnt starting

I'm using Pterodactyl

----------------

:/home/container$ cd src && npm run azuri
> azuri@2.0.0 azuri /home/container/src
> node app.mjs
internal/modules/cjs/loader.js:885
  const err = new Error(message);
              ^
Error: Cannot find module 'node:events'
Require stack:
- /home/container/src/node_modules/discord.js/src/client/BaseClient.js
- /home/container/src/node_modules/discord.js/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/container/src/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/container/src/node_modules/discord.js/src/client/BaseClient.js',
    '/home/container/src/node_modules/discord.js/src/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! azuri@2.0.0 azuri: `node app.mjs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the azuri@2.0.0 azuri script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/container/.npm/_logs/2022-09-15T21_56_36_007Z-debug.log

**Comment by finnie2006** [comment]
![afbeelding](https://user-images.githubusercontent.com/57916807/191914563-b25ec1e3-0010-4aec-b28a-334217a15b42.png)
